flowchart LR
  Start((開始)) -->|取得成功| viewing[閲覧]

  viewing -->|編集| editing[編集]
  editing --> edit_exit{編集終了}
  edit_exit -->|保存成功| return_viewing[閲覧へ戻る]
  edit_exit -->|キャンセル| return_viewing

  viewing -->|復習| reviewing[復習]
  reviewing --> review_exit{復習終了}
  review_exit -->|戻る| return_viewing
  review_exit -->|更新成功| return_viewing
